[package]
name = "gctk"
version = "0.1.0"
edition = "2024"

[dependencies]
gcode = { git = "https://github.com/bmgxyz/gcode-rs", rev = "9371cea" }
clap = { version = "4.5.42", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
